name: integration-hub-poc
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqledge
    networks:
      integration-hub-poc:
        aliases:
          - "sb-emulator"
  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      integration-hub-poc:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
  wpas-validator:
    container_name: wpas-validator
    build:
      context: ../wpas-validator
      dockerfile: ./Dockerfile
#    restart: always
  inbound-queue-listener:
    container_name: inbound-queue-listener
    profiles:
      - do-not-start
    build:
      context: ../dev-asb-listener
      dockerfile: ./Dockerfile
    depends_on:
      - emulator
    networks:
      integration-hub-poc:
        aliases:
          - "inbound-queue-listener"
    environment:
      CONNECTION_STRING: "${SB_CONNECTION_STRING}"
      QUEUE_NAME: "${INBOUND_QUEUE_NAME}"
  inbound-queue-producer:
    container_name: inbound-queue-producer
    profiles:
      - do-not-start
    build:
      context: ../dev-asb-producer
      dockerfile: ./Dockerfile
    depends_on:
      - emulator
    networks:
      integration-hub-poc:
        aliases:
          - "inbound-queue-producer"
    volumes:
      - ./testdata:/testdata
    environment:
      CONNECTION_STRING: "${SB_CONNECTION_STRING}"
      QUEUE_NAME: "${INBOUND_QUEUE_NAME}"
      FILENAME: "/testdata/test.xml"

networks:
  integration-hub-poc:

