//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package wales.nhs.dhcw.inthub.wpasHl7.xml;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wales.nhs.dhcw.inthub.wpasHl7.xml package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v4.0.5", date = "2025-03-04T12:15:27+01:00")
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wales.nhs.dhcw.inthub.wpasHl7.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MAINDATA }
     * 
     * @return
     *     the new instance of {@link MAINDATA }
     */
    public MAINDATA createMAINDATA() {
        return new MAINDATA();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION }
     */
    public MAINDATA.TRANSACTION createMAINDATATRANSACTION() {
        return new MAINDATA.TRANSACTION();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION.ACTREQOPTIONS }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION.ACTREQOPTIONS }
     */
    public MAINDATA.TRANSACTION.ACTREQOPTIONS createMAINDATATRANSACTIONACTREQOPTIONS() {
        return new MAINDATA.TRANSACTION.ACTREQOPTIONS();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION.OPADDONS }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION.OPADDONS }
     */
    public MAINDATA.TRANSACTION.OPADDONS createMAINDATATRANSACTIONOPADDONS() {
        return new MAINDATA.TRANSACTION.OPADDONS();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION.TRANSFERS }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION.TRANSFERS }
     */
    public MAINDATA.TRANSACTION.TRANSFERS createMAINDATATRANSACTIONTRANSFERS() {
        return new MAINDATA.TRANSACTION.TRANSFERS();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION.ACTREQOPTIONS.TEST }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION.ACTREQOPTIONS.TEST }
     */
    public MAINDATA.TRANSACTION.ACTREQOPTIONS.TEST createMAINDATATRANSACTIONACTREQOPTIONSTEST() {
        return new MAINDATA.TRANSACTION.ACTREQOPTIONS.TEST();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION.OPADDONS.OPADDON }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION.OPADDONS.OPADDON }
     */
    public MAINDATA.TRANSACTION.OPADDONS.OPADDON createMAINDATATRANSACTIONOPADDONSOPADDON() {
        return new MAINDATA.TRANSACTION.OPADDONS.OPADDON();
    }

    /**
     * Create an instance of {@link MAINDATA.TRANSACTION.TRANSFERS.TRANSFER }
     * 
     * @return
     *     the new instance of {@link MAINDATA.TRANSACTION.TRANSFERS.TRANSFER }
     */
    public MAINDATA.TRANSACTION.TRANSFERS.TRANSFER createMAINDATATRANSACTIONTRANSFERSTRANSFER() {
        return new MAINDATA.TRANSACTION.TRANSFERS.TRANSFER();
    }

}
